"""add column user_id in users_db

Revision ID: 08e9727a402b
Revises: 104fb69dda21
Create Date: 2026-04-09 20:16:12.610932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08e9727a402b'
down_revision: Union[str, Sequence[str], None] = '104fb69dda21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_db', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users_db', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_db', type_='foreignkey')
    op.drop_column('users_db', 'user_id')
    # ### end Alembic commands ###
