"""add column db_sslm_mode in table users_db

Revision ID: 53a46ef543ce
Revises: b8741d27b8a0
Create Date: 2026-04-12 12:37:16.538315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53a46ef543ce'
down_revision: Union[str, Sequence[str], None] = 'b8741d27b8a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_db', sa.Column(
        'db_ssl_mode', sa.Boolean(), nullable=False, default=sa.False_())
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_db', 'db_ssl_mode')
    # ### end Alembic commands ###
