"""add column executed in table sql_generate

Revision ID: b8741d27b8a0
Revises: 76ee66b0ccc5
Create Date: 2026-04-11 10:41:21.867616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8741d27b8a0'
down_revision: Union[str, Sequence[str], None] = '76ee66b0ccc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sql_generate', sa.Column(
        'executed', sa.Boolean(), nullable=False, server_default=sa.false()
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sql_generate', 'executed')
    # ### end Alembic commands ###
